# Generated by Django 5.0 on 2023-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('category', models.CharField(choices=[('TS', 'Футболки'), ('SS', 'Кофты'), ('HT', 'Головные уборы'), ('RG', 'Рашгарды'), ('CR', 'Шевроны'), ('FL', 'Флаги'), ('EQ', 'Снаряжение с разделением на СМБ и ИСБ')], max_length=2, verbose_name='Категория')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, upload_to='product/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
