# Generated by Django 5.0 on 2024-01-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
